### PR TITLE
fix: add exception handling when realPathFromUri is null

### LINKED ISSUE #2: realPathFromUri null
if realPathFromUri is null, app crashes.

### PR DESCRIPTION
**Pull request by jeeyunlee-fe**
When user select image which does not provide a physical file, like a cloud storage, realPathFromUri can be null. (cause it does not have correct path) This PR adds exception handling when realPathFromUri is null.

### CODE REVIEW

File: android/src/main/java/com/reactnativeimageselector/ImageSelectorModule.kt [hunk 1]
```diff
@@ -285,21 +287,44 @@ class ImageSelectorModule(reactContext: ReactApplicationContext) : ReactContextB
...
-                    val response = FileManager.createCacheFile(activity.applicationContext, realPathUri, globalOptions)
-                    this.callbackInvoker.let { callback ->
-                      if (callback != null) {
-                        callback.invoke(null, response)
-                        this.callbackInvoker = null
+                try {
+                  if (parsedUri != null) {
+                    if (activity != null) {
+                      var realPathFromUri = PathManager.getPathFromURI(context, parsedUri, globalOptions)
+                      if (realPathFromUri === null) throw NullPointerException("realPathFromUri is Null")
```
Comment (jeeyunlee-fe) [inline android/src/main/java/com/reactnativeimageselector/ImageSelectorModule.kt:294]: when realPathFromUri is null, throw error

File: android/src/main/java/com/reactnativeimageselector/ImageSelectorModule.kt [hunk 2]
```diff
@@ -285,21 +287,44 @@ class ImageSelectorModule(reactContext: ReactApplicationContext) : ReactContextB
...
+                      val response = FileManager.createCacheFile(activity.applicationContext, realPathUri, globalOptions)
+                      this.callbackInvoker.let { callback ->
+                        if (callback != null) {
+                          callback.invoke(null, response)
+                          this.callbackInvoker = null
+                        }
                       }
                     }
                   }
+                } catch (e: NullPointerException) {
```
Comment (jeeyunlee-fe) [inline android/src/main/java/com/reactnativeimageselector/ImageSelectorModule.kt:308]: catch error when realPathFromUri is null

File: android/src/main/java/com/reactnativeimageselector/ImageSelectorModule.kt [hunk 3]
```diff
@@ -285,21 +287,44 @@ class ImageSelectorModule(reactContext: ReactApplicationContext) : ReactContextB
...
+                  this.callbackInvoker.let { callback ->
+                    if (callback != null) {
+                      val error = Arguments.createMap()
+                      error.putInt("code", ErrorCode.notValidPath)
+                      error.putString("message", ErrorMessage.notValidPath + e.message)
+                      callback.invoke(error)
+                      this.callbackInvoker = null
+                    }
+                  }
+                } catch(e) {
```
Comment (jeeyunlee-fe) [inline android/src/main/java/com/reactnativeimageselector/ImageSelectorModule.kt:318]: catch error when other exception occurs

**Review by killi8n — APPROVED** [review]
